-   repo: https://github.com/aneel2023/magento2-pre-hooks
    rev: 2.0.1  # Use the ref you want to point at
    hooks:
    -   id: magento-phpcs
        args: ["--php=php8.1"]
    #-   id: magento-phpmd
    -   id: magento-phpunit
        args: ["--php=php8.1"]